server:
  port: 9527

spring:
  datasource:
    url: jdbc:mysql://120.27.152.254:3306/mk?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin111
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MKHikariCP
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 101.37.27.202
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

mybatis:
  type-aliases-package: com.mileworks.gen.system.domain,com.mileworks.gen.job.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null

mapper:
  mappers: com.mileworks.gen.common.config.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']

MK:
  # 是否在控制台打印 SQL
  showsql: false
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 3600
